In [1]:
import sys
print(sys.version)

3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0]


# Tensors

In [3]:
import torch
import numpy as np

## Initializing a Tensor

In [4]:
# Directly from data
data = [[1, 2], [3, 4]]
tc_data = torch.tensor(data)
print(tc_data, type(tc_data))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [5]:
# From a NumPy array
np_array = np.array(data)
print(type(np_array))
np_data = torch.from_numpy(np_array)
print(np_data, type(np_data))

<class 'numpy.ndarray'>
tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [6]:
# From another tensor
# Retains shape and datatype of the argument tensor
x_ones = torch.ones_like(tc_data)
print(x_ones)
x_rand = torch.rand_like(tc_data, dtype=torch.float)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.7063, 0.8315],
        [0.1560, 0.6106]])


In [7]:
# With random or constant values
# `shape` is a tuple of tensor dimensions.
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(rand_tensor, '\n', ones_tensor, '\n', zeros_tensor)

tensor([[0.5841, 0.9630, 0.8078],
        [0.5012, 0.5372, 0.6034]]) 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [8]:
# Attributes
tensor = torch.rand(3, 4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Operations

In [10]:
# Need to explicitly move tensors from CPU to GPU using `to` method
if torch.cuda.is_available():
    print('possible')
    tensor = tensor.to("cuda")
    print(f"Now device tensor is stored on: {tensor.device}")
else:
    print('not possible')

possible
Now device tensor is stored on: cuda:0


In [11]:
# Numpy-like indexing and slicing
tensor = torch.ones(4, 4)
print(tensor)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:, 1] = 0
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [12]:
# Joining tensors
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [16]:
# Arithmetic operations
print(tensor)
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
print(y2)
y3 = torch.rand_like(tensor)
print(y3)
torch.matmul(tensor, tensor.T) #out=y3

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[0.9775, 0.2598, 0.0605, 0.1446],
        [0.5322, 0.4900, 0.5945, 0.3693],
        [0.0151, 0.3011, 0.9084, 0.5020],
        [0.9472, 0.0220, 0.0404, 0.8633]])


tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [17]:
# Element-wise product
z1 = tensor*tensor
print(z1)
z2 = tensor.mul(tensor)
print(z2)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [23]:
# Single-element tensors
# can convert it to a Python numerical value using `item()`
agg = tensor.sum()
print(agg, type(agg))
agg_item = agg.item()
print(agg_item, type(agg_item))

tensor(12.) <class 'torch.Tensor'>
12.0 <class 'float'>


In [24]:
# In-place operations
# Operations that store the result into the operand, denoted by a `_` suffix
print(tensor)
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


## Bridge with NumPy
Tensors on the CPU and NumPy arrays can share their underlying memory locations, changing one will change the other.

In [26]:
# Tensor to NumPy array
t = torch.ones(5)
print(t)
n = t.numpy()
print(n)

t.add_(1)
print(t)
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [27]:
# Numpy array to Tensor
n = np.ones(5)
t = torch.from_numpy(n)
print(n, '\n', t)

np.add(n, 2, out=n)
print(n, '\n', t)

[1. 1. 1. 1. 1.] 
 tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[3. 3. 3. 3. 3.] 
 tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
